//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyStatement
    {
        public int MonthlyStatementID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> TotalDeposits { get; set; }
        public Nullable<decimal> TotalWithdrawals { get; set; }
        public Nullable<decimal> TotalTransfers { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
    
        public virtual User User { get; set; }
    }
}
