//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsGoal
    {
        public int SavingsGoalID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string GoalName { get; set; }
        public Nullable<decimal> GoalAmount { get; set; }
        public Nullable<decimal> CurrentSavings { get; set; }
    
        public virtual User User { get; set; }
    }
}
