//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> CardSourceID { get; set; }
        public Nullable<int> CardDestID { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string TransactionCurency { get; set; }
        public Nullable<int> MessageID { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Card Card1 { get; set; }
        public virtual Message Message { get; set; }
    }
}
